### ISSUE TITLE
 Pivot(Crosstab) Report 在dragdrop模式下没问题， 但是在sql 模式下报错

### ISSUE THREAD

**Issue by skywalkerhw** [dbface/issues#24]
![image](https://user-images.githubusercontent.com/13765913/89099055-3f579300-d41f-11ea-8bcd-a3e8c8793fcf.png)
![image](https://user-images.githubusercontent.com/13765913/89099060-4c748200-d41f-11ea-97e2-66d7dce65a07.png)

**Comment by jsding** [comment]
Pivot脚本，需要设置Pivot的rows columns values,否则无法取合适的字段。拖拽模式已经指定。
