### ISSUE TITLE
Chain Application  预览没有问题，但是打开报错

### ISSUE THREAD

**Issue by skywalkerhw** [dbface/issues#28]
![image](https://user-images.githubusercontent.com/13765913/89101582-ca428880-d433-11ea-9baa-59b1322af705.png)

**Comment by skywalkerhw** [comment]
再次编辑，页面错乱

**Comment by skywalkerhw** [comment]
![image](https://user-images.githubusercontent.com/13765913/89101607-0b3a9d00-d434-11ea-8481-0cf546f0cb57.png)

**Comment by jsding** [comment]
getBody() ---> getBody()->getContents()
