### ISSUE TITLE
CSV import 如果文件以tab分割，无法解析成列

### ISSUE THREAD

**Issue by skywalkerhw** [dbface/issues#44]
![image](https://user-images.githubusercontent.com/13765913/89114125-999e3580-d4ab-11ea-8ac7-98bdc91a73bd.png)

**Comment by skywalkerhw** [comment]
而且如果没有输入tablename ，错误信息不明确
![image](https://user-images.githubusercontent.com/13765913/89114154-dec26780-d4ab-11ea-940b-86499274d724.png)

**Comment by jsding** [comment]
此CSV非Tab分割
