### ISSUE TITLE
Query dashboard 编辑的时候没有显示已经加入的application,不好重新选择，而且无法去除应用

### ISSUE THREAD

**Issue by skywalkerhw** [dbface/issues#7]
![image](https://user-images.githubusercontent.com/13765913/89094399-0f47ca00-d3f6-11ea-861e-5046312d97bc.png)

**Comment by jsding** [comment]
这个控件替换掉，重新实现下

**Comment by jsding** [comment]
已经选择的应用，在选择列表中排除
